# Global registry instance


from dhenara.agent.dsl.inbuilt.flow_nodes.ai_model.tracing import ai_model_node_tracing_profile
from dhenara.agent.dsl.inbuilt.flow_nodes.command.tracing import command_node_tracing_profile
from dhenara.agent.dsl.inbuilt.flow_nodes.file_operation.tracing import file_operation_node_tracing_profile
from dhenara.agent.dsl.inbuilt.flow_nodes.folder_analyzer.tracing import folder_analyzer_node_tracing_profile
from dhenara.agent.observability.tracing.data import TracingProfileRegistry

tracing_profile_registry = TracingProfileRegistry()
tracing_profile_registry.register(ai_model_node_tracing_profile)
tracing_profile_registry.register(command_node_tracing_profile)
tracing_profile_registry.register(folder_analyzer_node_tracing_profile)
tracing_profile_registry.register(file_operation_node_tracing_profile)
